/**
 * Reference test: verify the Buck ABCD matches Buck_closed_V4.m.
 *
 * EXPECTED_A below was generated by the JS port for the default parameters
 * and independently confirmed against NumPy's eigenvalues. When you run
 * Buck_closed_V4.m in MATLAB with the default parameters, disp(A) should
 * match these values.
 *
 * Run with: node tests/buck.test.js
 */

import { buildABCD } from '../src/core/abcd.js';
import { buck } from '../src/converters/buck.js';

const w = 2 * Math.PI * 40e3;
const EXPECTED_A = [
  [ 0,         -2000,       0,         0,          0,         0,         0,     0 ],
  [ 6666.6667, -666.6667,   0,         0,          0,         0,         0,     0 ],
  [ 0,          0,          0,         w,         -2000,      0,         0,     0 ],
  [ 0,          0,         -w,         0,          0,        -2000,      0,     0 ],
  [ 0,          0,          6666.6667, 0,         -666.6667,  w,         0,     0 ],
  [ 0,          0,          0,         6666.6667, -w,        -666.6667,  0,     0 ],
  [ 0,         -1,          0,         0,          0,         0,         0,     0 ],
  [ -1,        -0.377,      0,         0,          0,         0,         94.75, 0 ],
];

export function testBuckABCD() {
  const parameters = Object.fromEntries(
    buck.parameters.map(p => [p.id, p.default])
  );
  const { A } = buildABCD(buck, parameters, { autotuneIfMissing: false });

  let failures = 0;
  for (let i = 0; i < 8; i++) {
    for (let j = 0; j < 8; j++) {
      if (Math.abs(A[i][j] - EXPECTED_A[i][j]) > 1e-3) {
        console.error(`A[${i}][${j}] mismatch: got ${A[i][j]}, expected ${EXPECTED_A[i][j]}`);
        failures++;
      }
    }
  }
  if (failures === 0) console.log('testBuckABCD: passed ✓');
  else throw new Error(`testBuckABCD: ${failures} mismatch(es)`);
}

testBuckABCD();
